# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'openweather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'R.swift'

  # Pods for openweather

  target 'openweatherTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Quick'
    pod 'Nimble'
    pod 'SwiftyJSON'
  end

end
